# Generated by Django 6.0.3 on 2026-03-21 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_exchange', models.CharField(max_length=100, verbose_name='primary exchange')),
                ('secondary_exchange', models.CharField(max_length=100, verbose_name='secondary exchange')),
                ('entry_spread', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='entry spread')),
                ('exit_spread', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='exit spread')),
                ('coin', models.CharField(max_length=20, verbose_name='coin')),
                ('coin_amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='coin amount')),
                ('order_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('auto', 'Авто')], default='auto', max_length=4, verbose_name='order type')),
                ('max_trades', models.PositiveIntegerField(default=10, verbose_name='max trades')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_configs', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'bot configuration',
                'verbose_name_plural': 'bot configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
