# Generated by Django 6.0.3 on 2026-03-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='primary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='primary exchange'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='secondary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='secondary exchange'),
        ),
    ]
