# Generated by Django 6.0.3 on 2026-03-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_botconfig_primary_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='close_ticks',
            field=models.PositiveIntegerField(default=1, verbose_name='close ticks'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='open_ticks',
            field=models.PositiveIntegerField(default=1, verbose_name='open ticks'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='primary_leverage',
            field=models.PositiveIntegerField(default=1, verbose_name='primary leverage'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='secondary_leverage',
            field=models.PositiveIntegerField(default=1, verbose_name='secondary leverage'),
        ),
    ]
