# Generated by Django 6.0.3 on 2026-04-04 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_botconfig_primary_exchange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmulationTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='trade amount')),
                ('primary_open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='primary open price')),
                ('secondary_open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='secondary open price')),
                ('open_spread', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='open spread')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='opened at')),
                ('primary_close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='primary close price')),
                ('secondary_close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='secondary close price')),
                ('close_spread', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='close spread')),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='profit percentage')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emulation_trades', to='bots.botconfig', verbose_name='bot configuration')),
            ],
            options={
                'verbose_name': 'emulation trade',
                'verbose_name_plural': 'emulation trades',
                'ordering': ['-opened_at'],
            },
        ),
    ]
