# Generated by Django 6.0.3 on 2026-04-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_emulationtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulationtrade',
            name='coin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='coin'),
        ),
        migrations.AddField(
            model_name='emulationtrade',
            name='order_type',
            field=models.CharField(blank=True, choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('auto', 'Авто')], max_length=4, null=True, verbose_name='order type'),
        ),
        migrations.AddField(
            model_name='emulationtrade',
            name='primary_exchange',
            field=models.CharField(blank=True, choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, null=True, verbose_name='primary exchange'),
        ),
        migrations.AddField(
            model_name='emulationtrade',
            name='secondary_exchange',
            field=models.CharField(blank=True, choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, null=True, verbose_name='secondary exchange'),
        ),
        migrations.AlterField(
            model_name='emulationtrade',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emulation_trades', to='bots.botconfig', verbose_name='bot configuration'),
        ),
    ]
