# Generated by Django 6.0.3 on 2026-04-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_emulationtrade_coin_emulationtrade_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emulationtrade',
            name='coin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='coin'),
        ),
    ]
