# Generated by Django 6.0.3 on 2026-04-04 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_emulationtrade_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emulationtrade',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emulation_trades', to='bots.botconfig', verbose_name='bot configuration'),
        ),
    ]
