# Generated by Django 6.0.3 on 2026-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_alter_emulationtrade_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50, verbose_name='coin')),
                ('primary_exchange', models.CharField(choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='primary exchange')),
                ('secondary_exchange', models.CharField(choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='secondary exchange')),
                ('order_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('auto', 'Авто')], max_length=4, verbose_name='order type')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('force_closed', 'Force Closed')], default='open', max_length=20, verbose_name='status')),
                ('close_reason', models.CharField(blank=True, choices=[('profit', 'Profit target reached'), ('timeout', 'Max duration exceeded'), ('manual', 'Manually closed'), ('shutdown', 'Graceful shutdown'), ('error', 'Error during monitoring')], max_length=20, null=True, verbose_name='close reason')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='coin amount')),
                ('leverage', models.PositiveIntegerField(default=1, verbose_name='leverage used')),
                ('primary_open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='primary open price')),
                ('secondary_open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='secondary open price')),
                ('primary_open_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='primary open order ID')),
                ('secondary_open_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='secondary open order ID')),
                ('open_spread', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='open spread')),
                ('open_commission', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='total open commission (USDT)')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='opened at')),
                ('primary_close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='primary close price')),
                ('secondary_close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='secondary close price')),
                ('primary_close_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='primary close order ID')),
                ('secondary_close_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='secondary close order ID')),
                ('close_spread', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='close spread')),
                ('close_commission', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='total close commission (USDT)')),
                ('profit_usdt', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='profit (USDT)')),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='profit (%)')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
            ],
            options={
                'verbose_name': 'trade',
                'verbose_name_plural': 'trades',
                'ordering': ['-opened_at'],
            },
        ),
    ]
