# Generated by Django 6.0.3 on 2026-04-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botconfig',
            name='close_ticks',
        ),
        migrations.RemoveField(
            model_name='botconfig',
            name='open_ticks',
        ),
    ]
