# Generated by Django 6.0.3 on 2026-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_remove_botconfig_close_ticks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='trade_mode',
            field=models.CharField(choices=[('emulator', 'Эмулятор'), ('real', 'Реальная торговля')], default='emulator', max_length=20, verbose_name='trade mode'),
        ),
    ]
