# Generated by Django 6.0.3 on 2026-04-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_botconfig_trade_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='trade_on_primary_exchange',
            field=models.BooleanField(default=True, verbose_name='trade on primary'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='trade_on_secondary_exchange',
            field=models.BooleanField(default=True, verbose_name='trade on secondary'),
        ),
    ]
