# Generated by Django 6.0.3 on 2026-04-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_botconfig_trade_on_primary_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='max_leg_drawdown_percent',
            field=models.FloatField(default=80.0, verbose_name='max leg drawdown %'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='max_trade_duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='max trade duration (m)'),
        ),
    ]
