# Generated by Django 6.0.3 on 2026-04-23 14:30

import apps.bots.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0014_botconfig_max_leg_drawdown_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='last_command',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('sync', 'Sync'), ('stop', 'Stop'), ('force-close', 'Force close')], max_length=20, verbose_name='last command'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='last_sync_error',
            field=models.TextField(blank=True, verbose_name='last sync error'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last synced at'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='service_url',
            field=models.URLField(default=apps.bots.models.default_bot_service_url, max_length=500, verbose_name='service url'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('error', 'Error'), ('archived', 'Archived')], default='stopped', max_length=20, verbose_name='runtime status'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='sync_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20, verbose_name='sync status'),
        ),
        migrations.AddField(
            model_name='trade',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_trades', to='bots.botconfig', verbose_name='bot configuration'),
        ),
        migrations.AddField(
            model_name='trade',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='primary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='primary exchange'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='secondary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='secondary exchange'),
        ),
        migrations.AlterField(
            model_name='emulationtrade',
            name='primary_exchange',
            field=models.CharField(blank=True, choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, null=True, verbose_name='primary exchange'),
        ),
        migrations.AlterField(
            model_name='emulationtrade',
            name='secondary_exchange',
            field=models.CharField(blank=True, choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, null=True, verbose_name='secondary exchange'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='primary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='primary exchange'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='secondary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('binance_spot', 'Binance Spot'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='secondary exchange'),
        ),
        migrations.CreateModel(
            name='TraderRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('service_url', models.URLField(max_length=500, verbose_name='service url')),
                ('primary_exchange', models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('gate', 'Gate'), ('mexc', 'MEXC')], max_length=20, verbose_name='primary exchange')),
                ('secondary_exchange', models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('gate', 'Gate'), ('mexc', 'MEXC')], max_length=20, verbose_name='secondary exchange')),
                ('use_testnet', models.BooleanField(default=False, verbose_name='use testnet')),
                ('trade_amount_usdt', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='trade amount (USDT)')),
                ('leverage', models.PositiveIntegerField(default=10, verbose_name='leverage')),
                ('max_concurrent_trades', models.PositiveIntegerField(default=3, verbose_name='max concurrent trades')),
                ('top_liquid_pairs_count', models.PositiveIntegerField(default=100, verbose_name='top liquid pairs count')),
                ('max_trade_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='max trade duration (m)')),
                ('max_leg_drawdown_percent', models.DecimalField(decimal_places=2, default=80, max_digits=6, verbose_name='max leg drawdown %')),
                ('open_threshold', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='open threshold')),
                ('close_threshold', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='close threshold')),
                ('orderbook_limit', models.PositiveIntegerField(default=50, verbose_name='orderbook limit')),
                ('chunk_size', models.PositiveIntegerField(default=10, verbose_name='chunk size')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('error', 'Error'), ('archived', 'Archived')], default='stopped', max_length=20, verbose_name='runtime status')),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20, verbose_name='sync status')),
                ('last_command', models.CharField(blank=True, choices=[('start', 'Start'), ('sync', 'Sync'), ('stop', 'Stop'), ('force-close', 'Force close')], max_length=20, verbose_name='last command')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='last sync error')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synced at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader_runtime_configs', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'trader runtime configuration',
                'verbose_name_plural': 'trader runtime configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trade',
            name='runtime_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='bots.traderruntimeconfig', verbose_name='runtime configuration'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(condition=models.Q(('bot__isnull', False), ('runtime_config__isnull', False), _negated=True), name='trade_single_runtime_source'),
        ),
        migrations.AddConstraint(
            model_name='traderruntimeconfig',
            constraint=models.CheckConstraint(condition=models.Q(('primary_exchange', models.F('secondary_exchange')), _negated=True), name='trader_runtime_config_distinct_exchanges'),
        ),
        migrations.AddConstraint(
            model_name='traderruntimeconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('owner',), name='unique_active_trader_runtime_config_per_owner'),
        ),
    ]
