# Generated by Django 6.0.3 on 2026-04-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_botconfig_last_command_botconfig_last_sync_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='primary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='primary exchange'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='secondary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='secondary exchange'),
        ),
        migrations.AlterField(
            model_name='emulationtrade',
            name='primary_exchange',
            field=models.CharField(blank=True, choices=[('binance_futures', 'Binance Futures'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, null=True, verbose_name='primary exchange'),
        ),
        migrations.AlterField(
            model_name='emulationtrade',
            name='secondary_exchange',
            field=models.CharField(blank=True, choices=[('binance_futures', 'Binance Futures'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, null=True, verbose_name='secondary exchange'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='primary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='primary exchange'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='secondary_exchange',
            field=models.CharField(choices=[('binance_futures', 'Binance Futures'), ('bybit_futures', 'Bybit Futures'), ('gate_futures', 'Gate Futures'), ('mexc_futures', 'Mexc Futures')], max_length=50, verbose_name='secondary exchange'),
        ),
        migrations.AlterField(
            model_name='traderruntimeconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
