# Generated by Django 6.0.3 on 2026-04-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_alter_botconfig_primary_exchange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderRuntimeConfigError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('start', 'Start'), ('sync', 'Sync'), ('stop', 'Stop'), ('runtime', 'Runtime'), ('exchange_health', 'Exchange health'), ('diagnostics', 'Diagnostics'), ('validation', 'Validation'), ('control_plane', 'Control plane')], max_length=50, verbose_name='error type')),
                ('error_text', models.TextField(verbose_name='error text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('runtime_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='bots.traderruntimeconfig', verbose_name='runtime configuration')),
            ],
            options={
                'verbose_name': 'trader runtime configuration error',
                'verbose_name_plural': 'trader runtime configuration errors',
                'ordering': ['-created_at'],
            },
        ),
    ]
