# Generated by Django 6.0.3 on 2026-05-11 18:35

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0017_traderruntimeconfigerror'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='close_commission',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='total close commission (USDT)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open_commission',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='total open commission (USDT)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='opened at'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_usdt',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='profit (USDT)'),
        ),
        migrations.AddConstraint(
            model_name='botconfig',
            constraint=models.CheckConstraint(condition=models.Q(('primary_exchange', models.F('secondary_exchange')), _negated=True), name='bot_config_distinct_exchanges'),
        ),
    ]
