# Generated by Django 6.0.3 on 2026-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0018_alter_trade_close_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='last_command',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('sync', 'Sync'), ('stop', 'Stop'), ('pause', 'Pause'), ('force-close', 'Force close')], max_length=20, verbose_name='last command'),
        ),
        migrations.AlterField(
            model_name='traderruntimeconfig',
            name='last_command',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('sync', 'Sync'), ('stop', 'Stop'), ('pause', 'Pause'), ('force-close', 'Force close')], max_length=20, verbose_name='last command'),
        ),
    ]
