# Generated by Django 6.0.3 on 2026-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0021_unique_open_trade_per_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='min_trade_interval_seconds',
            field=models.PositiveIntegerField(default=10, verbose_name='min trade interval (s)'),
        ),
    ]
