# Generated by Django 6.0.3 on 2026-06-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40)),
                ('timeframe', models.CharField(max_length=8)),
                ('natr_multiplier', models.FloatField()),
                ('min_gap', models.PositiveIntegerField()),
                ('direction', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('both', 'both')], max_length=4)),
                ('max_breakout_seconds', models.PositiveIntegerField()),
                ('min_move_pct', models.FloatField()),
                ('candles', models.PositiveIntegerField()),
                ('candles_analyzed', models.PositiveIntegerField()),
                ('range_from', models.BigIntegerField()),
                ('range_to', models.BigIntegerField()),
                ('breakouts_found', models.PositiveIntegerField()),
                ('evaluated', models.PositiveIntegerField()),
                ('matched', models.PositiveIntegerField()),
                ('unmatched', models.PositiveIntegerField()),
                ('match_rate', models.FloatField()),
                ('up_found', models.PositiveIntegerField()),
                ('up_matched', models.PositiveIntegerField()),
                ('down_found', models.PositiveIntegerField()),
                ('down_matched', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelAnalysisBreakout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('level_time', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('top', 'top'), ('bottom', 'bottom')], max_length=6)),
                ('direction', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=4)),
                ('touches', models.PositiveIntegerField()),
                ('breakout_candle_time', models.BigIntegerField()),
                ('cross_time', models.BigIntegerField(blank=True, null=True)),
                ('reach_time', models.BigIntegerField(blank=True, null=True)),
                ('elapsed_ms', models.BigIntegerField(blank=True, null=True)),
                ('move_pct', models.FloatField(blank=True, null=True)),
                ('matched', models.BooleanField()),
                ('reason', models.CharField(max_length=32)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakouts', to='levels.levelanalysis')),
            ],
            options={
                'ordering': ['breakout_candle_time'],
            },
        ),
        migrations.AddIndex(
            model_name='levelanalysis',
            index=models.Index(fields=['owner', 'symbol', '-created_at'], name='levels_leve_owner_i_a6faed_idx'),
        ),
    ]
