# Generated by Django 6.0.3 on 2026-06-07 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_favoritecoin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('only_favorites', models.BooleanField(default=False)),
                ('timeframe', models.CharField(default='1m', max_length=8)),
                ('natr_multiplier', models.FloatField(default=0.3)),
                ('min_gap', models.PositiveIntegerField(default=12)),
                ('min_volume', models.FloatField(default=0)),
                ('distance_mode', models.CharField(choices=[('pct', 'pct'), ('natr', 'natr')], default='pct', max_length=4)),
                ('distance_value', models.FloatField(default=1.0)),
                ('chat_id', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_notification_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'level notification config',
                'verbose_name_plural': 'level notification configs',
            },
        ),
    ]
