# Generated by Django 6.0.3 on 2026-04-16 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExchangeKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binance_api_key', models.CharField(blank=True, max_length=255)),
                ('binance_secret', models.CharField(blank=True, max_length=255)),
                ('bybit_api_key', models.CharField(blank=True, max_length=255)),
                ('bybit_secret', models.CharField(blank=True, max_length=255)),
                ('gate_api_key', models.CharField(blank=True, max_length=255)),
                ('gate_secret', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user exchange keys',
                'verbose_name_plural': 'user exchange keys',
            },
        ),
    ]
