# Generated by Django 6.0.3 on 2026-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userexchangekeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexchangekeys',
            name='mexc_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userexchangekeys',
            name='mexc_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
