# Generated by Django 6.0.3 on 2026-06-11 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userexchangekeys_mexc_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSectionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bots', models.BooleanField(default=True, verbose_name='Боты (/)')),
                ('screener', models.BooleanField(default=True, verbose_name='Скринер (/screener)')),
                ('levels', models.BooleanField(default=True, verbose_name='Уровни (/levels)')),
                ('pnl', models.BooleanField(default=True, verbose_name='PnL (/pnl)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user section access',
                'verbose_name_plural': 'user section access',
            },
        ),
    ]
